Moved to sysconfig style of storage

diff --git a/.local/bin/slackstack b/.local/bin/slackstack
--- a/.local/bin/slackstack
+++ b/.local/bin/slackstack
@@ -1,4 +1,4 @@
-#!/usr/bin/startx
+#!/usr/bin/bash
 ################################
 ###### iDigitalFlame 2018 ######
 #                              #
@@ -17,8 +17,20 @@
 #                              #
 ########## SPACEPORT ###########
 ################################
-## X init Script
-# iDigitalFlame
+## Slack Auto Opener
+# Opens all my Slack URLs set in my Slack Auto file.
 
-xrdb =merge ~/.Xresources
-exec i3
+SLACK_LIST="$HOME/.config/slack-auto.txt"
+
+python3 $HOME/.local/bin/i3/new.py 2> /dev/null
+if [ $? -ne 0 ]; then
+    printf "Failed to create new workspace!\n"
+    exit 1
+fi
+i3-msg layout tabbed 2> /dev/null
+if [ $? -ne 0 ]; then
+    printf "Failed to set workspace layout!\n"
+    exit 1
+fi
+sg firewall-web -c "for url in \$(cat $SLACK_LIST); do screen -dm sh -c \"export GTK_THEME=null; /usr/bin/surf -mDfIkPBSng -c ~/.config/Cookies/slack-cookies.txt \$url\"; done"
+exit 0
