Updates to theme libraries and fixes for the Tank and SMD compatibility.

diff --git a/.local/bin/smb-connect b/.local/bin/smb-connect
--- a/.local/bin/smb-connect
+++ b/.local/bin/smb-connect
@@ -1,6 +1,6 @@
 #!/usr/bin/bash
 ################################
-###### iDigitalFlame 2018 ######
+###### iDigitalFlame 2019 ######
 #                              #
 #            -/`               #
 #            -yy-   :/`        #
@@ -17,29 +17,78 @@
 #                              #
 ########## SPACEPORT ###########
 ################################
-## SMB Connect
+## SMB Connecter
 # iDigitalFlame
 
-if [ $# -lt 2 ]; then
-  printf "smb-connect [-f] <username> <share_path>\n"
-  exit 1
+if [ $# -lt 2 ] || [ $# -gt 3 ]; then
+    printf "smb [--reset] <domain\\\user|user> <share>\n"
+    exit 1
 fi
 
-if [ $# -eq 3 ]; then
-    smbusr="$2"
-    smbshare="$3"
+sanatized_username=$(echo $1 | sed -e 's/\\/-/g' | sed -e 's/@/-/g')
+
+if [ $# -eq 3 ] && [ "$1" == "--reset" ]; then
+    printf "" | gnome-keyring-query set smb-$sanatized_username
+    1=$2
+    2=$3
 else
-    smbusr="$1"
-    smbshare="$2"
+    if [ $# -eq 3 ]; then
+        printf "smb [--reset] <domain\\\user|user> <share>\n"
+        exit 1
+    fi
 fi
-if [ ! -z "$(echo $smbusr | grep '/')" ]; then
-    smbdom=$(echo $smbusr | awk -F'/' '{print $1}')
-    smbusr=$(echo $smbusr | awk -F'/' '{print $2}')
+
+user="$1"
+share="$2"
+domain=""
+
+if [ ! -z "$(echo $user | grep '\\')" ]; then
+    domain=$(echo $user | awk -F'\' '{print $1}')
+    user=$(echo $user | awk -F'\' '{print $2}')
 else
-    smbdom=""
+    if [ ! -z "$(echo $user | grep '@')" ]; then
+        domain=$(echo $user | awk -F'@' '{print $1}')
+        user=$(echo $user | awk -F'@' '{print $2}')
+    fi
 fi
-smbfldr=$(echo "$smbshare" | awk -F'/' '{print $NF}')
-smbwkrg=$(echo "$smbdom" | awk -F'.' '{print $1}')
+
+folder=$(echo "$share" | awk -F'/' '{print $NF}')
+server=$(echo "$share" | awk -F'/' '{print $3}')
+
+if [ ! -z "$(mount | grep $folder | grep $server)" ]; then
+    printf "Share \"$folder\" on \"$server\" seems to already be mounted!\n"
+    exit 1
+fi
+
+set_password=0
+password=$(gnome-keyring-query get smb-$sanatized_username 2> /dev/null)
+while [ -z "$password" ]; do
+    set_password=1
+    printf "Password for $1: "
+    read -s password
+    printf "\n"
+done
+
+if [ $set_password -eq 1 ]; then
+    printf "$password" | gnome-keyring-query set smb-$sanatized_username
+fi
+printf "domain $domain, user $user, pass $password"
+
+
+
+mkdir -p "/tmp/.mounts/$USER/$server-folder" 2> /dev/null
+if [ $? -ne 0 ]; then
+    printf "Could not creating mouting folder \"/tmp/.mounts/$USER/$server-folder\"!\n"
+    exit 1
+fi
+
+
+printf "$user\n$domain\n$password\n" | sudo /opt/spaceport/sbin/smb-mount "$server/$folder" "$smbmnt"
+
+echo "$folder, $server"
+
+exit 1
+
 if [ $# -eq 3 ];then
     printf "" | gnome-keyring-query set smb-connect-$smbwkrg-$smbusr
     smbpwd=""
