Fixes

diff --git a/.bin/smb-connect b/.bin/smb-connect
--- a/.bin/smb-connect
+++ b/.bin/smb-connect
@@ -18,8 +18,7 @@
 ########## SPACEPORT ###########
 ################################
 ## SMB Connect
-# Connects a SMB folder and uses the keyring
-# Updated 06/05/2018
+# iDigitalFlame 2018
 
 if [ $# -lt 2 ]; then
   printf "smb-connect [-f] <username> <share_path>\n"
@@ -27,50 +26,50 @@ if [ $# -lt 2 ]; then
 fi
 
 if [ $# -eq 3 ]; then
-  SMB_USER="$2"
-  SMB_SHARE="$3"
+    SMB_USER="$2"
+    SMB_SHARE="$3"
 else
-  SMB_USER="$1"
-  SMB_SHARE="$2"
+    SMB_USER="$1"
+    SMB_SHARE="$2"
 fi
 if [ ! -z "$(echo $SMB_USER | grep '/')" ]; then
-  SMB_DOMAIN=$(echo $SMB_USER | awk -F'/' '{print $1}')
-  SMB_USER=$(echo $SMB_USER | awk -F'/' '{print $2}')
+    SMB_DOMAIN=$(echo $SMB_USER | awk -F'/' '{print $1}')
+    SMB_USER=$(echo $SMB_USER | awk -F'/' '{print $2}')
 else
-  SMB_DOMAIN=""
+    SMB_DOMAIN=""
 fi
 SMB_FOLDER=$(echo "$SMB_SHARE" | awk -F'/' '{print $NF}')
 SMB_NAME=$(echo "$SMB_FOLDER" | sed -e 's/ //g')
 SMB_WORKGROUP=$(echo "$SMB_DOMAIN" | awk -F'.' '{print $1}')
 if [ $# -eq 3 ];then
-  printf "" | gnome-keyring-query set smb-connect-$SMB_WORKGROUP-$SMB_USER
-  SMB_PASSWORD=""
+    printf "" | gnome-keyring-query set smb-connect-$SMB_WORKGROUP-$SMB_USER
+    SMB_PASSWORD=""
 else
-  SMB_PASSWORD=$(gnome-keyring-query get smb-connect-$SMB_WORKGROUP-$SMB_USER)
+    SMB_PASSWORD=$(gnome-keyring-query get smb-connect-$SMB_WORKGROUP-$SMB_USER)
 fi
 while [ -z "$SMB_PASSWORD" ]; do
-  printf "Password: "
-  read -s SMB_PASSWORD
+    printf "Password: "
+    read -s SMB_PASSWORD
 done
 if [ -z "$SMB_PASSWORD" ]; then
-  printf "A password is required!\n"
-  exit 1
+    printf "A password is required!\n"
+    exit 1
 fi
 printf "$SMB_PASSWORD" | gnome-keyring-query set smb-connect-$SMB_WORKGROUP-$SMB_USER
 SMB_MOUNT="/tmp/.mounts/$USER/smb-$(echo $SMB_FOLDER | sed -e 's/\$//g')"
 SMB_NUMBER=0
 if [ ! -z "$(mount | grep $SMB_MOUNT)" ]; then
-  printf "\"$SMB_MOUNT\" is already mounted!\n"
-  exit 1
+    printf "\"$SMB_MOUNT\" is already mounted!\n"
+    exit 1
 fi
 if [ ! -d "$SMB_MOUNT" ]; then
-  mkdir -p "$SMB_MOUNT"
+    mkdir -p "$SMB_MOUNT"
 fi
 sudo /opt/spaceport/bin/msmb "$SMB_SHARE" "$SMB_MOUNT" "vers=3.0,username=\"$SMB_USER\",domain=\"$SMB_DOMAIN\",workgroup=\"$SMB_WORKGROUP\",password=\"$SMB_PASSWORD\",uid=$USER,gid=$USER,file_mode=0750,dir_mode=0750"
 if [ $? -ne 0 ]; then
-  printf "There was a problem mounting \"$SMB_SHARE\"!\n"
+    printf "There was a problem mounting \"$SMB_SHARE\"!\n"
 else
-  printf "\"$SMB_SHARE\" mounted to \"$SMB_MOUNT\"\n"
+    printf "\"$SMB_SHARE\" mounted to \"$SMB_MOUNT\"\n"
 fi
 SMB_PASSWORD=""
 SMB_DOMAIN=""
